/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "stdlib.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0             (GUI_ID_USER + 0x00)
#define ID_GRAPH_0             (GUI_ID_USER + 0x01)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 5, 5, 470, 262, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
GRAPH_DATA_Handle PhaseDataA;
GRAPH_DATA_Handle PhaseDataB;
GRAPH_DATA_Handle PhaseDataC;
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  // USER START (Optionally insert additional variables)
	WM_HWIN hItem;
  // USER END

  switch (pMsg->MsgId) {
  // USER START (Optionally insert additional message handling)
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_WHITE);
    //
    // Graph YT
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);

    PhaseDataA = GRAPH_DATA_YT_Create(GUI_ORANGE, 470, NULL, 0);
    PhaseDataB = GRAPH_DATA_YT_Create(GUI_YELLOW, 470, NULL, 0);
    PhaseDataC = GRAPH_DATA_YT_Create(GUI_GREEN, 470, NULL, 0);

    GRAPH_AttachData(hItem, PhaseDataA);
    GRAPH_AttachData(hItem, PhaseDataB);
    GRAPH_AttachData(hItem, PhaseDataC);
    GRAPH_SetGridVis(hItem, 1);
    break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void MainTask(void)
{
	CreateWindow();
	int AngleA=0;
	int AngleB=0x555;
	int AngleC=0xAAA;
	while(1) {
		int NewPhaseDataA =GUI_sin(AngleA)/10;
		int NewPhaseDataB =GUI_sin(AngleB)/10;
		int NewPhaseDataC =GUI_sin(AngleC)/10;
		AngleA+=10;
		AngleB+=10;
		AngleC+=10;
		if(AngleA==0xfff){
			AngleA=0;
			AngleB=0x555;
			AngleC=0xAAA;
		}
		GRAPH_DATA_YT_AddValue(PhaseDataA, NewPhaseDataA+131);
		GRAPH_DATA_YT_AddValue(PhaseDataB, NewPhaseDataB+131);
		GRAPH_DATA_YT_AddValue(PhaseDataC, NewPhaseDataC+131);
		GUI_Exec();
		GUI_Delay(10);
	}
}
// USER END

/*************************** End of file ****************************/
